# Generated by Django 3.2 on 2022-01-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('phn_no', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
